spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300
    mongodb:
      uri: mongodb://localhost/gtm-api-dev
      database: gtm-api
  cache:
    type: redis
server:
  port: 8080
  compression:
    enabled: true
    mime-types: font/woff2,image/svg+xml,application/font-woff,application/json,application/xml,application/javascript,text/html,text/xml,text/plain,text/javascript,text/css
logging:
  level:
    org.apache.http: ERROR
    org.springframework:
      web: ERROR
      data: ERROR
      security: ERROR
      cache: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: ERROR
    dev.local.gtm.api: ERROR
  file: gtm-api.log
  file.max-history: 20
  pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
management:
  endpoints:
    # 默认激活所有监控管理接口
    enabled-by-default: true
    web:
      # base-path: /management
      # 让所有监控接口都接受 web 访问
      exposure:
        include: "*"
      # 设置跨域
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: ALWAYS

---

spring:
  profiles: dev
  devtools:
    remote:
      secret: thisismysecret
  data:
    mongodb:
      database: gtm-api-dev
      host: localhost
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300
logging:
  level:
    org.apache.http: DEBUG
    org.springframework:
        web:
          client.RestTemplate: DEBUG
        data:
          elasticsearch:
            core: DEBUG
          mongodb:
            core:
              MongoTemplate: DEBUG
        security: DEBUG
        cache: DEBUG
    dev.local.gtm.api: DEBUG

---

spring:
  profiles: test
  data:
    mongodb:
      uri: "mongodb://localhost/gtm-api-test"
      database: gtm-api-test
  cache:
    type: none
logging:
  level:
    org.apache.http: DEBUG
    org.springframework:
      web:
        client.RestTemplate: DEBUG
      data: DEBUG
      security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    dev.local.gtm.api: DEBUG
---

spring:
  profiles: prod
  data:
    mongodb:
      uri: "mongodb://mongo/gtm-api"
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: elasticsearch:9300
      properties:
        client.transport.sniff: false
  redis:
    host: redis
    port: 6379

